### PR TITLE
Update 0072_a-vingança-do-pássaro-de-mel.md

### PR DESCRIPTION
**Pull request by espensj**

### CODE REVIEW

**Comment by dohliam** [comment]
Just noticed this has been open for a while... is this change still needed?

**Comment by espensj** [comment]
Not sure. What are the changes?

**Comment by espensj** [comment]
Gingile is correct. I noticed that most of the story had "Gengile".

**Comment by dohliam** [comment]
Thanks.... Merged!

**Comment by dohliam** [comment]
Thanks... merged!

**Pull request merged**
